import Head from "next/head";
import Layout from "../Components/Layout";
import styles from "../styles/Home.module.css";
import SearchInput from "../Components/SearchInput";
import CountriesTable from "../Components/CountriesTable";
import { useState } from "react";
export default function Home({ countries }) {
  console.log("countries", countries);

  const [keyword, setkeyword] = useState("")

  // const filteredCountries = countries.filter((country) => country.altSpellings[1].toLowerCase().includes(keyword);

  const filteredCountries = countries.filter(
    (country) =>
      country.startOfWeek.toLowerCase().includes(keyword)
  );

  console.log("filteredCountries",filteredCountries);
    
  return (
    <div>
      <Head>
        <title>Countries Population Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.counts}>Found {countries.length} countries</div>
        <SearchInput />
        <CountriesTable countries={filteredCountries} />
      </Layout>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const countries = await res.json();
  return {
    props: {
      countries,
    },
  };
};
