import Head from "next/head";
import Layout from "../Components/Layout";
import styles from "../styles/Home.module.css";
// import SearchInput from "../Components/SearchInput";
import CountriesTable from "../Components/CountriesTable";
export default function Home({ countries }) {
  console.log("countries", countries);

  return (
    <>
      <Head>
        <title>All About All Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.inputContainer}>
          <div className={styles.counts}>
            Found {countries.length} countries
          </div>
          {/* <div className={styles.input}>
            {" "}
            <SearchInput />
          </div> */}
        </div>

        <CountriesTable countries={countries} />
      </Layout>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const countries = await res.json();
  return {
    props: {
      countries,
    },
  };
};
